export default [
    {id: 'any', name: 'Any Category'},
    {id:  9, name: 'General Knowledge'},
    {id: 16, name: 'Entertainment: Board Games'},
    {id: 10, name: 'Entertainment: Books'},
    {id: 32, name: 'Entertainment: Cartoon &amp; Animations'},
    {id: 29, name: 'Entertainment: Comics'},
    {id: 11, name: 'Entertainment: Film'},
    {id: 31, name: 'Entertainment: Japanese Anime &amp; Manga'},
    {id: 12, name: 'Entertainment: Music'},
    {id: 13, name: 'Entertainment: Musicals &amp; Theatres'},
    {id: 14, name: 'Entertainment: Television'},
    {id: 15, name: 'Entertainment: Video Games'},
    {id: 17, name: 'Science &amp; Nature'},
    {id: 18, name: 'Science: Computers'},
    {id: 30, name: 'Science: Gadgets'},
    {id: 19, name: 'Science: Mathematics'},
    {id: 27, name: 'Animals'},
    {id: 25, name: 'Art'},
    {id: 26, name: 'Celebrities'},
    {id: 22, name: 'Geography'},
    {id: 23, name: 'History'},
    {id: 20, name: 'Mythology'},
    {id: 24, name: 'Politics'},
    {id: 21, name: 'Sports'},
    {id: 28, name: 'Vehicles'},
];
